from MHCRFB import MHCRFB as MHCRFB
from AttentionMHCRFB import AMHCRFB as AMHCRFB
from ClassBaseGuideAMHCRFB import CBGAMHCRFB as CBGAMHCRFB
from RClassBaseGuideAMHCRFB import RCBGAMHCRFB as RCBGAMHCRFB
from SRCBGAMHCARFB import SRCBGAMHCARFB as SRCBGAMHCARFB
from SCBGAMHCRFB import SCBGAMHCRFB as SCBGAMHCRFB
from ASRCBGAMHCRFB import ASRCBGAMHCRFB as ASRCBGAMHCRFB
from SCASRCBGAMHCRFB import SCASRCBGAMHCRFB as SCASRCBGAMHCRFB
from NVNSWASRCBGAMHCRFB import NVNSWASRCBGAMHCRFB as NVNSWASRCBGAMHCRFB
from NSWASRCBGAMHCRFB import NSWASRCBGAMHCRFB as NSWASRCBGAMHCRFB
from RNVNSWASRCBGAMHCRFB import RNVNSWASRCBGAMHCRFB as RNVNSWASRCBGAMHCRFB
from NVNSWRASRCBGAMHCRFB import NVNSWRASRCBGAMHCRFB as NVNSWRASRCBGAMHCRFB
from PSNVNSWASRCBGAMHCRFB import PSNVNSWASRCBGAMHCRFB as PSNVNSWASRCBGAMHCRFB
from PMHOAMHCRFB import PMHOAMHCRFB as PMHOAMHCRFB
def get_model(model_choice_str: str):
    model_choice = {
        'MHCRFB':MHCRFB,
        'AMHCRFB':AMHCRFB,
        'CBGAMHCRFB':CBGAMHCRFB,
        'RCBGAMHCRFB':RCBGAMHCRFB,
        'SCBGAMHCRFB':SCBGAMHCRFB,
        'SRCBGAMHCARFB':SRCBGAMHCARFB,
        'ASRCBGAMHCRFB':ASRCBGAMHCRFB,
        'SCASRCBGAMHCRFB':SCASRCBGAMHCRFB,
        'NVNSWASRCBGAMHCRFB':NVNSWASRCBGAMHCRFB,
        'NSWASRCBGAMHCRFB':NSWASRCBGAMHCRFB,
        'RNVNSWASRCBGAMHCRFB':RNVNSWASRCBGAMHCRFB,
        'NVNSWRASRCBGAMHCRFB':NVNSWRASRCBGAMHCRFB,
        'PSNVNSWASRCBGAMHCRFB':PSNVNSWASRCBGAMHCRFB,
        'PMHOAMHCRFB':PMHOAMHCRFB
    }
    return model_choice[model_choice_str]